#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi

if echo "$VERSION" | grep -q -e '^v.*' ; then
    UI_INDEX="local"
fi
UI_INDEX=${UI_INDEX:-"https://rancher-octopus.s3-accelerate.amazonaws.com/ui/latest/index.html"}

# Inject Setting values
DEFAULT_VALUES="{\"ui-index\":\"${UI_INDEX}\"}"

LINKFLAGS="-X github.com/cnrancher/octopus-api-server.Version=$VERSION"
LINKFLAGS="-X github.com/cnrancher/octopus-api-server.GitCommit=$COMMIT $LINKFLAGS"
LINKFLAGS="-X github.com/cnrancher/octopus-api-server/pkg/settings.InjectDefaults=$DEFAULT_VALUES $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/octopus-api-server
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/octopus-api-server-darwin
    GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/octopus-api-server-windows
fi
